services:
  jenkins_server:
    image: jenkins/jenkins:lts
    container_name: jenkins_server
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - ./data/jenkins_home:/var/jenkins_home
    environment:
      JAVA_OPTS: "-Djenkins.install.runSetupWizard=false"
    networks:
      - jenkins_network
  jenkins_agent:
    image: jenkins/ssh-agent:alpine-jdk17
    container_name: jenkins_agent
    platform: linux/amd64
    ports:
      - "4444:22"
    environment:
      - JENKINS_AGENT_SSH_PUBKEY=$JENKINS_AGENT_SSH_PUBKEY
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - jenkins_network

volumes:
  jenkins_home:

networks:
  jenkins_network:
    driver: bridge
